### ISSUE TITLE
npm run zip and yarn zip is failed ... it is returning errors

### ISSUE THREAD

**Issue by hamzahabib2000** [MikeiLL/divi-scripts#1]
npm run zip and yarn zip is failed ... it is returning errors
I'm using nvm ... and tried the following node version:
v12.0.0
v13.0.0
v13.14.0
v14.0.0

Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
fs.js:125
    throw err;
    ^
Error: EPERM: operation not permitted, symlink 'D:\apachehtdocs\divi\wp-content\plugins\divi3\node_modules\divi-scripts\config\Gruntfile.js' -> 'D:\apachehtdocs\divi\wp-content\plugins\divi3\Gruntfile.js'
    at Object.symlinkSync (fs.js:962:3)
    at Object.<anonymous> (D:\apachehtdocs\divi\wp-content\plugins\divi3\node_modules\divi-scripts\scripts\zip.js:34:4)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! divi3@0.1.0 zip: `divi-scripts build && divi-scripts zip`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the divi3@0.1.0 zip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hamza\AppData\Roaming\npm-cache\_logs\2022-05-22T15_52_24_149Z-debug.log

**Comment by MikeiLL** [comment]
I haven't worked with this in a while. You might get better results with the original codebase it's a slight modification of: https://github.com/elegantthemes/create-divi-extension/blob/master/packages/divi-scripts/template/README.md

**Comment by hamzahabib2000** [comment]
I'm also using the version you have mentioned, mentioned here because this sounds a separate repository/package

**Comment by MikeiLL** [comment]
I wish I had more time to help troubleshoot with you at this time. I think the key is in `Error: EPERM: operation not permitted`. Possibly file permissions?

**Comment by hamzahabib2000** [comment]
there cannot be file permission error, because I'm using cmd as administrator(windows) 10, there is something else phishy ...
